### ISSUE TITLE
Zbay sends multiple duplicate messages.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#107]
https://rumblefishdev.atlassian.net/browse/ZBAY-906

**Comment by NorbertBodziony** [comment]
I just merged a fix.

**Comment by NorbertBodziony** [comment]
@holmesworcester can we close this issue ?

**Comment by holmesworcester** [comment]
yes, i'm no longer seeing this bug.

**Comment by holmesworcester** [comment]
I'm still seeing this bug in "offer messages", that is, messages to sellers about an offer.

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/213678/86517288-c7815300-bdf5-11ea-9fcd-3f3b56a2c0eb.png">

**Comment by holmesworcester** [comment]
this isn't a release blocker but it is a priority to fix it. @NorbertBodziony

**Comment by NorbertBodziony** [comment]
#309 fix
